version: '3.8'

services:
  email-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs